# Data Preprocessing on Breast Cancer Dataset - 05/24/2026 - vingut8011

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report

from xgboost import XGBClassifier

print("Student ID: vingut8011")
print("Date: 05/24/2026")

Student ID: vingut8011
Date: 05/24/2026

In [7]:
df = pd.read_csv(r"C:\Users\iaasi\Documents\SDC485DocumentsECPI_AI_Class\breastCancerDataset.csv")

print("First 5 rows:")
display(df.head())

print("Dataset info:")
df.info()

print("Summary statistics:")
display(df.describe())

First 5 rows:

,ID,Diagnosis,radius1,texture1,perimeter1,area1,smoothness1,compactness1,concavity1,concave_points1,...,radius3,texture3,perimeter3,area3,smoothness3,compactness3,concavity3,concave_points3,symmetry3,fractal_dimension3
0,0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

Dataset info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 32 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  569 non-null    int64
 1   Diagnosis           569 non-null    object
 2   radius1             569 non-null    float64
 3   texture1            569 non-null    float64
 4   perimeter1          569 non-null    float64
 5   area1               569 non-null    float64
 6   smoothness1         569 non-null    float64
 7   compactness1        569 non-null    float64
 8   concavity1          569 non-null    float64
 9   concave_points1     569 non-null    float64
 10  symmetry1           569 non-null    float64
 11  fractal_dimension1  569 non-null    float64
 12  radius2             569 non-null    float64
 13  texture2            569 non-null    float64
 14  perimeter2          569 non-null    float64
 15  area2               569 non-null    float64
 16  smoothness2         569 non-null    float64
 17  compactness2        569 non-null    float64
 18  concavity2          569 non-null    float64
 19  concave_points2     569 non-null    float64
 20  symmetry2           569 non-null    float64
 21  fractal_dimension2  569 non-null    float64
 22  radius3             569 non-null    float64
 23  texture3            569 non-null    float64
 24  perimeter3          569 non-null    float64
 25  area3               569 non-null    float64
 26  smoothness3         569 non-null    float64
 27  compactness3        569 non-null    float64
 28  concavity3          569 non-null    float64
 29  concave_points3     569 non-null    float64
 30  symmetry3           569 non-null    float64
 31  fractal_dimension3  569 non-null    float64
dtypes: float64(30), int64(1), object(1)
memory usage: 142.4+ KB
Summary statistics:

,ID,radius1,texture1,perimeter1,area1,smoothness1,compactness1,concavity1,concave_points1,symmetry1,...,radius3,texture3,perimeter3,area3,smoothness3,compactness3,concavity3,concave_points3,symmetry3,fractal_dimension3
count,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,...,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000
mean,284.000000,14.127292,19.289649,91.969033,654.889104,0.096360,0.104341,0.088799,0.048919,0.181162,...,16.269190,25.677223,107.261213,880.583128,0.132369,0.254265,0.272188,0.114606,0.290076,0.083946
std,164.400426,3.524049,4.301036,24.298981,351.914129,0.014064,0.052813,0.079720,0.038803,0.027414,...,4.833242,6.146258,33.602542,569.356993,0.022832,0.157336,0.208624,0.065732,0.061867,0.018061
min,0.000000,6.981000,9.710000,43.790000,143.500000,0.052630,0.019380,0.000000,0.000000,0.106000,...,7.930000,12.020000,50.410000,185.200000,0.071170,0.027290,0.000000,0.000000,0.156500,0.055040
25%,142.000000,11.700000,16.170000,75.170000,420.300000,0.086370,0.064920,0.029560,0.020310,0.161900,...,13.010000,21.080000,84.110000,515.300000,0.116600,0.147200,0.114500,0.064930,0.250400,0.071460
50%,284.000000,13.370000,18.840000,86.240000,551.100000,0.095870,0.092630,0.061540,0.033500,0.179200,...,14.970000,25.410000,97.660000,686.500000,0.131300,0.211900,0.226700,0.099930,0.282200,0.080040
75%,426.000000,15.780000,21.800000,104.100000,782.700000,0.105300,0.130400,0.130700,0.074000,0.195700,...,18.790000,29.720000,125.400000,1084.000000,0.146000,0.339100,0.382900,0.161400,0.317900,0.092080
max,568.000000,28.110000,39.280000,188.500000,2501.000000,0.163400,0.345400,0.426800,0.201200,0.304000,...,36.040000,49.540000,251.200000,4254.000000,0.222600,1.058000,1.252000,0.291000,0.663800,0.207500

In [5]:
import os
print(os.getcwd())

C:\Users\iaasi

In [6]:
os.listdir()

['.anaconda',
 '.cagent',
 '.conda',
 '.config',
 '.continuum',
 '.docker',
 '.dotnet',
 '.gitconfig',
 '.idea',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.keras',
 '.lesshst',
 '.matplotlib',
 '.nuget',
 '.packettracer',
 '.python_history',
 '.templateengine',
 '.VirtualBox',
 '.vscode',
 '.vscode-shared',
 'abstraction_pa',
 'Advanced EDA Workshop.ipynb',
 'Advanced_EDA_Workshop.ipynb',
 'AmazonReview_NeuralNetwork_vingut8011.ipynb',
 'anaconda3',
 'anaconda_projects',
 'AppData',
 'Apple',
 'Application Data',
 'Cisco Packet Tracer 8.2.2',
 'CLionProjects',
 'code',
 'Contacts',
 'Cookies',
 'Data Preprocessing on Breast Cancer Datase.ipynb',
 'Data_Preprocessing.ipynb',
 'Desktop',
 'Documents',
 'Downloads',
 'Favorites',
 'GP_Python_AI_Techniques.ipynb',
 'GP_Python_Predictive.ipynb',
 'Gradient Boosting Regression on Diabetes Dataset.ipynb',
 'Links',
 'Local Settings',
 'Microsoft',
 'Music',
 'My Documents',
 'MyFirstApp',
 'NetHood',
 'New folder',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{68407e35-4390-11ef-b0c8-00155d012b0b}.TM.blf',
 'NTUSER.DAT{68407e35-4390-11ef-b0c8-00155d012b0b}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{68407e35-4390-11ef-b0c8-00155d012b0b}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'OneDrive',
 'PA_AmazonReviewData.xlsx',
 'PA_Instacart_Data.csv',
 'Predictive_Model_vingut8011',
 'PrintHood',
 'PycharmProjects',
 'Recent',
 'Saved Games',
 'Searches',
 'SendTo',
 'source',
 'Start Menu',
 'Templates',
 'Untitled.ipynb',
 'Untitled1.ipynb',
 'Untitled2.ipynb',
 'Untitled3.ipynb',
 'Use Basic AI Techniques.ipynb',
 'Videos',
 'VirtualBox VMs']

# Step 1/2: Load the Dataset

Date: 05/24/2026

Student ID: vingut8011

In [8]:
print("Dataset Info:")
df.info()

print("\nSummary Statistics:")
display(df.describe())

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 32 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  569 non-null    int64
 1   Diagnosis           569 non-null    object
 2   radius1             569 non-null    float64
 3   texture1            569 non-null    float64
 4   perimeter1          569 non-null    float64
 5   area1               569 non-null    float64
 6   smoothness1         569 non-null    float64
 7   compactness1        569 non-null    float64
 8   concavity1          569 non-null    float64
 9   concave_points1     569 non-null    float64
 10  symmetry1           569 non-null    float64
 11  fractal_dimension1  569 non-null    float64
 12  radius2             569 non-null    float64
 13  texture2            569 non-null    float64
 14  perimeter2          569 non-null    float64
 15  area2               569 non-null    float64
 16  smoothness2         569 non-null    float64
 17  compactness2        569 non-null    float64
 18  concavity2          569 non-null    float64
 19  concave_points2     569 non-null    float64
 20  symmetry2           569 non-null    float64
 21  fractal_dimension2  569 non-null    float64
 22  radius3             569 non-null    float64
 23  texture3            569 non-null    float64
 24  perimeter3          569 non-null    float64
 25  area3               569 non-null    float64
 26  smoothness3         569 non-null    float64
 27  compactness3        569 non-null    float64
 28  concavity3          569 non-null    float64
 29  concave_points3     569 non-null    float64
 30  symmetry3           569 non-null    float64
 31  fractal_dimension3  569 non-null    float64
dtypes: float64(30), int64(1), object(1)
memory usage: 142.4+ KB

Summary Statistics:

,ID,radius1,texture1,perimeter1,area1,smoothness1,compactness1,concavity1,concave_points1,symmetry1,...,radius3,texture3,perimeter3,area3,smoothness3,compactness3,concavity3,concave_points3,symmetry3,fractal_dimension3
count,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,...,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000
mean,284.000000,14.127292,19.289649,91.969033,654.889104,0.096360,0.104341,0.088799,0.048919,0.181162,...,16.269190,25.677223,107.261213,880.583128,0.132369,0.254265,0.272188,0.114606,0.290076,0.083946
std,164.400426,3.524049,4.301036,24.298981,351.914129,0.014064,0.052813,0.079720,0.038803,0.027414,...,4.833242,6.146258,33.602542,569.356993,0.022832,0.157336,0.208624,0.065732,0.061867,0.018061
min,0.000000,6.981000,9.710000,43.790000,143.500000,0.052630,0.019380,0.000000,0.000000,0.106000,...,7.930000,12.020000,50.410000,185.200000,0.071170,0.027290,0.000000,0.000000,0.156500,0.055040
25%,142.000000,11.700000,16.170000,75.170000,420.300000,0.086370,0.064920,0.029560,0.020310,0.161900,...,13.010000,21.080000,84.110000,515.300000,0.116600,0.147200,0.114500,0.064930,0.250400,0.071460
50%,284.000000,13.370000,18.840000,86.240000,551.100000,0.095870,0.092630,0.061540,0.033500,0.179200,...,14.970000,25.410000,97.660000,686.500000,0.131300,0.211900,0.226700,0.099930,0.282200,0.080040
75%,426.000000,15.780000,21.800000,104.100000,782.700000,0.105300,0.130400,0.130700,0.074000,0.195700,...,18.790000,29.720000,125.400000,1084.000000,0.146000,0.339100,0.382900,0.161400,0.317900,0.092080
max,568.000000,28.110000,39.280000,188.500000,2501.000000,0.163400,0.345400,0.426800,0.201200,0.304000,...,36.040000,49.540000,251.200000,4254.000000,0.222600,1.058000,1.252000,0.291000,0.663800,0.207500

# Step 3: Preprocess the Data

Date: 05/24/2026

Student ID: vingut8011

In [9]:
print("Missing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows Before Removal:")
print(df.duplicated().sum())

df = df.drop_duplicates()

print("\nDuplicate Rows After Removal:")
print(df.duplicated().sum())

Missing Values:
ID                    0
Diagnosis             0
radius1               0
texture1              0
perimeter1            0
area1                 0
smoothness1           0
compactness1          0
concavity1            0
concave_points1       0
symmetry1             0
fractal_dimension1    0
radius2               0
texture2              0
perimeter2            0
area2                 0
smoothness2           0
compactness2          0
concavity2            0
concave_points2       0
symmetry2             0
fractal_dimension2    0
radius3               0
texture3              0
perimeter3            0
area3                 0
smoothness3           0
compactness3          0
concavity3            0
concave_points3       0
symmetry3             0
fractal_dimension3    0
dtype: int64

Duplicate Rows Before Removal:
0

Duplicate Rows After Removal:
0

# Step 4: Feature Selection and Train/Test Split

Date: 05/24/2026

Student ID: vingut8011

In [10]:
Diagnosis

NameError: name 'Diagnosis' is not defined

In [11]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X = df.drop(columns=["Diagnosis"])
y = df["Diagnosis"]

# Encode M and B values
encoder = LabelEncoder()
y = encoder.fit_transform(y)

# Standardize concavity1 and concavity3
scaler = StandardScaler()

X[["concavity1", "concavity3"]] = scaler.fit_transform(
    X[["concavity1", "concavity3"]]
)

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.30,
    random_state=42
)

print("Training Data Shape:", X_train.shape)
print("Testing Data Shape:", X_test.shape)

Training Data Shape: (398, 31)
Testing Data Shape: (171, 31)

In [12]:
print(df.columns)

Index(['ID', 'Diagnosis', 'radius1', 'texture1', 'perimeter1', 'area1',
       'smoothness1', 'compactness1', 'concavity1', 'concave_points1',
       'symmetry1', 'fractal_dimension1', 'radius2', 'texture2', 'perimeter2',
       'area2', 'smoothness2', 'compactness2', 'concavity2', 'concave_points2',
       'symmetry2', 'fractal_dimension2', 'radius3', 'texture3', 'perimeter3',
       'area3', 'smoothness3', 'compactness3', 'concavity3', 'concave_points3',
       'symmetry3', 'fractal_dimension3'],
      dtype='object')

In [13]:
concavity1
concavity3

NameError: name 'concavity1' is not defined

In [14]:
print(df.columns)

Index(['ID', 'Diagnosis', 'radius1', 'texture1', 'perimeter1', 'area1',
       'smoothness1', 'compactness1', 'concavity1', 'concave_points1',
       'symmetry1', 'fractal_dimension1', 'radius2', 'texture2', 'perimeter2',
       'area2', 'smoothness2', 'compactness2', 'concavity2', 'concave_points2',
       'symmetry2', 'fractal_dimension2', 'radius3', 'texture3', 'perimeter3',
       'area3', 'smoothness3', 'compactness3', 'concavity3', 'concave_points3',
       'symmetry3', 'fractal_dimension3'],
      dtype='object')

In [15]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X = df.drop(columns=["Diagnosis"])
y = df["Diagnosis"]

encoder = LabelEncoder()
y = encoder.fit_transform(y)

scaler = StandardScaler()

X[["concavity1", "concavity3"]] = scaler.fit_transform(
    X[["concavity1", "concavity3"]]
)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.30,
    random_state=42
)

print("Training Data Shape:", X_train.shape)
print("Testing Data Shape:", X_test.shape)

Training Data Shape: (398, 31)
Testing Data Shape: (171, 31)

# Step 5: Implement SVM

Date: 05/24/2026

Student ID: vingut8011

In [16]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report

svm_model = SVC()

svm_model.fit(X_train, y_train)

svm_predictions = svm_model.predict(X_test)

print("SVM Accuracy Score:")
print(accuracy_score(y_test, svm_predictions))

print("\nClassification Report:")
print(classification_report(y_test, svm_predictions))

SVM Accuracy Score:
0.935672514619883

Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.97      0.95       108
           1       0.95      0.87      0.91        63

    accuracy                           0.94       171
   macro avg       0.94      0.92      0.93       171
weighted avg       0.94      0.94      0.94       171

# Step 6: Apply GridSearchCV for SVM Hyperparameter Tuning

Date: 05/24/2026

Student ID: vingut8011

In [17]:
from sklearn.model_selection import GridSearchCV

# Parameter grid
svm_param_grid = {
    "C": [0.1, 1, 10, 100],
    "kernel": ["linear", "rbf", "poly"]
}

# GridSearchCV
svm_grid = GridSearchCV(
    SVC(),
    svm_param_grid,
    cv=5
)

# Fit model
svm_grid.fit(X_train, y_train)

# Best parameters
print("Best SVM Parameters:")
print(svm_grid.best_params_)

# Best model
best_svm = svm_grid.best_estimator_

# Predictions
tuned_svm_predictions = best_svm.predict(X_test)

# Accuracy
print("\nTuned SVM Accuracy Score:")
print(accuracy_score(y_test, tuned_svm_predictions))

# Classification report
print("\nTuned SVM Classification Report:")
print(classification_report(y_test, tuned_svm_predictions))

Best SVM Parameters:
{'C': 1, 'kernel': 'linear'}

Tuned SVM Accuracy Score:
0.9649122807017544

Tuned SVM Classification Report:
              precision    recall  f1-score   support

           0       0.99      0.95      0.97       108
           1       0.93      0.98      0.95        63

    accuracy                           0.96       171
   macro avg       0.96      0.97      0.96       171
weighted avg       0.97      0.96      0.97       171

# Step 7: Implement XGBoost

Date: 05/24/2026

Student ID: vingut8011

In [18]:
from xgboost import XGBClassifier

xgb_model = XGBClassifier(
    eval_metric="logloss",
    random_state=42
)

xgb_model.fit(X_train, y_train)

xgb_predictions = xgb_model.predict(X_test)

print("XGBoost Accuracy Score:")
print(accuracy_score(y_test, xgb_predictions))

print("\nClassification Report:")
print(classification_report(y_test, xgb_predictions))

XGBoost Accuracy Score:
0.9766081871345029

Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.98      0.98       108
           1       0.97      0.97      0.97        63

    accuracy                           0.98       171
   macro avg       0.97      0.97      0.97       171
weighted avg       0.98      0.98      0.98       171

# Step 8: Apply GridSearchCV for XGBoost Hyperparameter Tuning

Date: 05/24/2026

Student ID: vingut8011

In [19]:
from sklearn.model_selection import GridSearchCV

# Parameter grid
xgb_param_grid = {
    "n_estimators": [50, 100],
    "learning_rate": [0.1, 0.2],
    "max_depth": [3, 4]
}

# GridSearchCV
xgb_grid = GridSearchCV(
    XGBClassifier(
        eval_metric="logloss",
        random_state=42
    ),
    xgb_param_grid,
    cv=5
)

# Fit model
xgb_grid.fit(X_train, y_train)

# Best parameters
print("Best XGBoost Parameters:")
print(xgb_grid.best_params_)

# Best model
best_xgb = xgb_grid.best_estimator_

# Predictions
tuned_xgb_predictions = best_xgb.predict(X_test)

# Accuracy
print("\nTuned XGBoost Accuracy Score:")
print(accuracy_score(y_test, tuned_xgb_predictions))

# Classification report
print("\nTuned XGBoost Classification Report:")
print(classification_report(y_test, tuned_xgb_predictions))

Best XGBoost Parameters:
{'learning_rate': 0.1, 'max_depth': 4, 'n_estimators': 100}

Tuned XGBoost Accuracy Score:
0.9649122807017544

Tuned XGBoost Classification Report:
              precision    recall  f1-score   support

           0       0.97      0.97      0.97       108
           1       0.95      0.95      0.95        63

    accuracy                           0.96       171
   macro avg       0.96      0.96      0.96       171
weighted avg       0.96      0.96      0.96       171

# Step 9: Analyze and Interpret

Date: 05/24/2026

Student ID: vingut8011

## Analyze and Interpret

Bias could be introduced into this dataset if the data does not equally represent all patient groups. For example, if the dataset contains more samples from certain age groups or populations, the model may perform better for those groups and less accurately for others. Bias can be reduced by using more balanced datasets, collecting data from diverse groups, and testing the model on different populations.

The tuned SVM and tuned XGBoost models were compared using accuracy score and classification reports. Both models performed very well on the dataset. The XGBoost model performed slightly better because it produced a high accuracy score and strong precision and recall values. XGBoost is effective because it combines multiple decision trees to improve prediction accuracy and reduce errors.